
repos:
- repo: local
  hooks:
  - id: lint
    entry: flake8
    args: [--max-line-length=90]
    name: Lint
    language: system
    types: [file, python]
- repo: local
  hooks:
  - id: test
    name: Unit Tests
    entry: python manage.py
    args: [test]
    pass_filenames: false
    language: system
    types: [file, python]
