# Generated by Django 3.1 on 2020-08-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='classification',
            field=models.CharField(blank=True, choices=[(1, 'Trabalho'), (2, 'Atividade Fisica'), (3, 'Lazer'), (4, 'Deslocamento')], max_length=32, null=True, verbose_name='Classification'),
        ),
    ]
