# Generated by Django 3.1 on 2020-08-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_auto_20200822_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='classification',
            field=models.IntegerField(blank=True, choices=[(1, 'Trabalho'), (2, 'Atividade Fisica'), (3, 'Lazer'), (4, 'Deslocamento')], null=True),
        ),
    ]
